services:
  - type: web
    name: farm-game
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///farm_game.db"
    autoDeploy: true
